# Todo : item_texts.py
item_texts = {
    "undefined": "Pas défini",
    "switch_to_lecteur_undefined": "Callback switch_to_lecteur non défini.",
    "no_file_link": "Aucun lien de fichier fourni.",
    "direct_link_failed": "Lien direct non obtenu.",
    "image_click_error": "Erreur dans on_image_clicked",
    "missing_client_or_link": "Client 1fichier ou lien manquant.",
    "getting_direct_link": "Récupération du lien de téléchargement direct...",
    "direct_link_retrieved": "Lien direct récupéré",
    "direct_download_error": "Erreur téléchargement via URL directe",
    "resume_from": "Reprise depuis",
    "bytes": "octets",
    "resume_download_error": "Erreur download avec reprise",
    "file_size_to_open": "Taille du fichier à ouvrir",
    "file_not_exist_or_empty": "Fichier inexistant ou vide. Annulation.",
    "direct_execute_exe": "Exécution directe d'un .exe détecté",
    "file_open_error": "Erreur lors de l'ouverture du fichier",
    "unable_refresh_token": "Impossible de rafraîchir le token",
    "item_not_found": "Item avec le lien",
    "unable_get_uid": "Impossible d'obtenir l'UID utilisateur",
    "unable_get_token": "Impossible d'obtenir le token Firebase",
    "item_deleted": "Item supprimé avec succès",
    "delete_error": "Erreur lors de la suppression",
    "user_not_connected": "Utilisateur non connecté à Firebase",
    "unable_check_connection": "Impossible de vérifier la connexion",
    "file_already_exists": "Le fichier",
    "at": "à",
    "item_not_in_db": "Item non trouvé dans la base de données locale",
    "download_already_in_progress": "Téléchargement déjà en cours pour",
    "download_error": "Erreur de téléchargement pour",
    "download_start_error": "Erreur lors du lancement du téléchargement",
    "download_success": "Fichier téléchargé avec succès à",
    "download_failed": "Échec du téléchargement pour",
    "post_download_error": "Erreur lors du traitement post-téléchargement",
    "local_path_updated": "Chemin local",
    "in_firebase": "mis à jour dans Firebase",
    "firebase_update_error": "Erreur lors de la mise à jour Firebase",
    "french": "Français",
    "english": "Anglais",
    "spanish": "Espagnol",
    "german": "Allemand",
    "italian": "Italien",
    "portuguese": "Portugais",
    "russian": "Russe",
    "chinese": "Chinois",
    "japanese": "Japonais",
    "korean": "Coréen",
    "arabic": "Arabe"
}
